name: CI/CD Pipeline
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to AWS ECR
      uses: aws-actions/amazon-ecr-login@v1
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: us-east-1
    - name: Build, tag, and push image to ECR
      run: |
        docker build -t 600627364901.dkr.ecr.us-east-1.amazonaws.com/pal-final-test:latest .
        docker push 600627364901.dkr.ecr.us-east-1.amazonaws.com/pal-final-test:latest
    - name: Deploy to ECS
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: arn:aws:ecs:us-east-1:600627364901:task-definition/pal-task
        service: pal-service
        cluster: pal-cluster